# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: db/devwfachallenge
  username: matty
  password: 'P0wernine.'
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: db/productionvfachallenge
  pool: 5
  timeout: 5000
